#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BitfiWallet.Resource", IsApplication=true)]

namespace BitfiWallet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::BitfiWallet.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::BitfiWallet.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::BitfiWallet.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int metaButtonBarButtonStyle = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int metaButtonBarStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int DarkGreen = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int black = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int black2 = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int black3 = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int black_overlay = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int colorAccent = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int colorOffWhite = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int colorOffWhite2 = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int colorPrimary = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int colorPrimary2 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int colorPrimary3 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int colorPrimary4 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int colorPrimaryDark = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int colorPrimaryDarkD = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int colorWhite = 2131099666;
			
			// aapt resource value: 0x7f060006
			public const int gray = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int gray2 = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int green = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int space = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040009
			public const int activity_horizontal_margin = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int activity_vertical_margin = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int fab_margin = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int margin_huge = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int margin_large = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int margin_medium = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int margin_small = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int margin_tiny = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int page_margin = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int standard_touch_target_size = 2130968581;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle_shape = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int circular_progress_bar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int deviceiddark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_icon_battery = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_icon_battery_low = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_icon_battery_low_large = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_icon_battery_on_charge = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_icon_network = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_icon_wifi = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_icon_wifi_disabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_icon_wifi_disabled_large = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_icons_devmessenger_circle = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_icons_paymentaddress = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_iconwalletbalance = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int layout_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int layout_bg_press = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int layout_bg_pressSpace = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int layout_bgSpace = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int layout_nm = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int logo2_svg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int logo_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int logo_lightgreen = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int logo_svg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int perm_group_status_bar = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int selector = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int selectorEnter = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int selectorNumeric = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int selectorSpace = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int btnAddresses = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int btnBalances = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int btnMessage = 2131165206;
			
			// aapt resource value: 0x7f070049
			public const int btnSendMessage = 2131165257;
			
			// aapt resource value: 0x7f070017
			public const int btnWalletID = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int btnWifi = 2131165209;
			
			// aapt resource value: 0x7f070090
			public const int button_0 = 2131165328;
			
			// aapt resource value: 0x7f070087
			public const int button_1 = 2131165319;
			
			// aapt resource value: 0x7f070088
			public const int button_2 = 2131165320;
			
			// aapt resource value: 0x7f070089
			public const int button_3 = 2131165321;
			
			// aapt resource value: 0x7f07008a
			public const int button_4 = 2131165322;
			
			// aapt resource value: 0x7f07008b
			public const int button_5 = 2131165323;
			
			// aapt resource value: 0x7f07008c
			public const int button_6 = 2131165324;
			
			// aapt resource value: 0x7f07008d
			public const int button_7 = 2131165325;
			
			// aapt resource value: 0x7f07008e
			public const int button_8 = 2131165326;
			
			// aapt resource value: 0x7f07008f
			public const int button_9 = 2131165327;
			
			// aapt resource value: 0x7f07009b
			public const int button_A = 2131165339;
			
			// aapt resource value: 0x7f0700a9
			public const int button_B = 2131165353;
			
			// aapt resource value: 0x7f0700a7
			public const int button_C = 2131165351;
			
			// aapt resource value: 0x7f0700ad
			public const int button_CAPS = 2131165357;
			
			// aapt resource value: 0x7f07009d
			public const int button_D = 2131165341;
			
			// aapt resource value: 0x7f070093
			public const int button_E = 2131165331;
			
			// aapt resource value: 0x7f07009e
			public const int button_F = 2131165342;
			
			// aapt resource value: 0x7f07009f
			public const int button_G = 2131165343;
			
			// aapt resource value: 0x7f0700a0
			public const int button_H = 2131165344;
			
			// aapt resource value: 0x7f070098
			public const int button_I = 2131165336;
			
			// aapt resource value: 0x7f0700a1
			public const int button_J = 2131165345;
			
			// aapt resource value: 0x7f0700a2
			public const int button_K = 2131165346;
			
			// aapt resource value: 0x7f0700a3
			public const int button_L = 2131165347;
			
			// aapt resource value: 0x7f0700ab
			public const int button_M = 2131165355;
			
			// aapt resource value: 0x7f0700aa
			public const int button_N = 2131165354;
			
			// aapt resource value: 0x7f070099
			public const int button_O = 2131165337;
			
			// aapt resource value: 0x7f07009a
			public const int button_P = 2131165338;
			
			// aapt resource value: 0x7f070091
			public const int button_Q = 2131165329;
			
			// aapt resource value: 0x7f070094
			public const int button_R = 2131165332;
			
			// aapt resource value: 0x7f07009c
			public const int button_S = 2131165340;
			
			// aapt resource value: 0x7f0700a4
			public const int button_SHIFT = 2131165348;
			
			// aapt resource value: 0x7f0700ae
			public const int button_SPACE = 2131165358;
			
			// aapt resource value: 0x7f070095
			public const int button_T = 2131165333;
			
			// aapt resource value: 0x7f070097
			public const int button_U = 2131165335;
			
			// aapt resource value: 0x7f0700a8
			public const int button_V = 2131165352;
			
			// aapt resource value: 0x7f070092
			public const int button_W = 2131165330;
			
			// aapt resource value: 0x7f0700a6
			public const int button_X = 2131165350;
			
			// aapt resource value: 0x7f070096
			public const int button_Y = 2131165334;
			
			// aapt resource value: 0x7f0700a5
			public const int button_Z = 2131165349;
			
			// aapt resource value: 0x7f0700ac
			public const int button_delete = 2131165356;
			
			// aapt resource value: 0x7f0700af
			public const int button_enter = 2131165359;
			
			// aapt resource value: 0x7f0700b5
			public const int contentFrame = 2131165365;
			
			// aapt resource value: 0x7f070079
			public const int forgetButton = 2131165305;
			
			// aapt resource value: 0x7f07000b
			public const int imageView1 = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int imageView2 = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int imageView3 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int imageViewB1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int imageViewB2 = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int imageViewW1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int imageViewW2 = 2131165189;
			
			// aapt resource value: 0x7f07007a
			public const int label = 2131165306;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout11 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout12 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout124 = 2131165205;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout14 = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout4 = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout7 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayoutBattery = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayoutWifi = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int linearLayoutllM = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int linearLayoutllM2 = 2131165187;
			
			// aapt resource value: 0x7f0700b3
			public const int linlaHeaderProgress = 2131165363;
			
			// aapt resource value: 0x7f0700b0
			public const int linlaHeaderProgressS = 2131165360;
			
			// aapt resource value: 0x7f07001b
			public const int llMessages = 2131165211;
			
			// aapt resource value: 0x7f070026
			public const int mwbutton_0 = 2131165222;
			
			// aapt resource value: 0x7f07001d
			public const int mwbutton_1 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int mwbutton_2 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int mwbutton_3 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int mwbutton_4 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int mwbutton_5 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int mwbutton_6 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int mwbutton_7 = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int mwbutton_8 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int mwbutton_9 = 2131165221;
			
			// aapt resource value: 0x7f070031
			public const int mwbutton_A = 2131165233;
			
			// aapt resource value: 0x7f070045
			public const int mwbutton_AT = 2131165253;
			
			// aapt resource value: 0x7f07003f
			public const int mwbutton_B = 2131165247;
			
			// aapt resource value: 0x7f07003d
			public const int mwbutton_C = 2131165245;
			
			// aapt resource value: 0x7f070043
			public const int mwbutton_CAPS = 2131165251;
			
			// aapt resource value: 0x7f070033
			public const int mwbutton_D = 2131165235;
			
			// aapt resource value: 0x7f070029
			public const int mwbutton_E = 2131165225;
			
			// aapt resource value: 0x7f070034
			public const int mwbutton_F = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int mwbutton_G = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int mwbutton_H = 2131165238;
			
			// aapt resource value: 0x7f07002e
			public const int mwbutton_I = 2131165230;
			
			// aapt resource value: 0x7f070037
			public const int mwbutton_J = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int mwbutton_K = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int mwbutton_L = 2131165241;
			
			// aapt resource value: 0x7f070041
			public const int mwbutton_M = 2131165249;
			
			// aapt resource value: 0x7f070040
			public const int mwbutton_N = 2131165248;
			
			// aapt resource value: 0x7f07002f
			public const int mwbutton_O = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int mwbutton_P = 2131165232;
			
			// aapt resource value: 0x7f070027
			public const int mwbutton_Q = 2131165223;
			
			// aapt resource value: 0x7f070044
			public const int mwbutton_Quote = 2131165252;
			
			// aapt resource value: 0x7f07002a
			public const int mwbutton_R = 2131165226;
			
			// aapt resource value: 0x7f070032
			public const int mwbutton_S = 2131165234;
			
			// aapt resource value: 0x7f07003a
			public const int mwbutton_SHIFT = 2131165242;
			
			// aapt resource value: 0x7f070048
			public const int mwbutton_SPACE = 2131165256;
			
			// aapt resource value: 0x7f070047
			public const int mwbutton_SemiC = 2131165255;
			
			// aapt resource value: 0x7f07002b
			public const int mwbutton_T = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int mwbutton_U = 2131165229;
			
			// aapt resource value: 0x7f070046
			public const int mwbutton_UnderS = 2131165254;
			
			// aapt resource value: 0x7f07003e
			public const int mwbutton_V = 2131165246;
			
			// aapt resource value: 0x7f070028
			public const int mwbutton_W = 2131165224;
			
			// aapt resource value: 0x7f07003c
			public const int mwbutton_X = 2131165244;
			
			// aapt resource value: 0x7f07002c
			public const int mwbutton_Y = 2131165228;
			
			// aapt resource value: 0x7f07003b
			public const int mwbutton_Z = 2131165243;
			
			// aapt resource value: 0x7f070042
			public const int mwbutton_delete = 2131165250;
			
			// aapt resource value: 0x7f07004c
			public const int okButton = 2131165260;
			
			// aapt resource value: 0x7f07007b
			public const int ovinf = 2131165307;
			
			// aapt resource value: 0x7f07007c
			public const int ovt1 = 2131165308;
			
			// aapt resource value: 0x7f0700b2
			public const int ovt1S = 2131165362;
			
			// aapt resource value: 0x7f07007d
			public const int ovt1b = 2131165309;
			
			// aapt resource value: 0x7f07007e
			public const int ovt2 = 2131165310;
			
			// aapt resource value: 0x7f07007f
			public const int ovt3 = 2131165311;
			
			// aapt resource value: 0x7f070080
			public const int pos0 = 2131165312;
			
			// aapt resource value: 0x7f070082
			public const int pos1 = 2131165314;
			
			// aapt resource value: 0x7f070085
			public const int pos2 = 2131165317;
			
			// aapt resource value: 0x7f0700b4
			public const int progressBar = 2131165364;
			
			// aapt resource value: 0x7f0700b1
			public const int progressBarS = 2131165361;
			
			// aapt resource value: 0x7f070081
			public const int tag1 = 2131165313;
			
			// aapt resource value: 0x7f070084
			public const int tag2 = 2131165316;
			
			// aapt resource value: 0x7f07004b
			public const int textviewPassword = 2131165259;
			
			// aapt resource value: 0x7f07004a
			public const int textviewSSID = 2131165258;
			
			// aapt resource value: 0x7f070083
			public const int ttag1 = 2131165315;
			
			// aapt resource value: 0x7f070086
			public const int ttag2 = 2131165318;
			
			// aapt resource value: 0x7f07001c
			public const int tvMessage = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int txtAppCode2 = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int txtAppCode22 = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int txtBPercent = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int txtBatteryLow = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int txtNoWifi = 2131165196;
			
			// aapt resource value: 0x7f070056
			public const int wbutton_0 = 2131165270;
			
			// aapt resource value: 0x7f07004d
			public const int wbutton_1 = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int wbutton_2 = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int wbutton_3 = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int wbutton_4 = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int wbutton_5 = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int wbutton_6 = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int wbutton_7 = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int wbutton_8 = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int wbutton_9 = 2131165269;
			
			// aapt resource value: 0x7f070061
			public const int wbutton_A = 2131165281;
			
			// aapt resource value: 0x7f070075
			public const int wbutton_AT = 2131165301;
			
			// aapt resource value: 0x7f07006f
			public const int wbutton_B = 2131165295;
			
			// aapt resource value: 0x7f07006d
			public const int wbutton_C = 2131165293;
			
			// aapt resource value: 0x7f070073
			public const int wbutton_CAPS = 2131165299;
			
			// aapt resource value: 0x7f070063
			public const int wbutton_D = 2131165283;
			
			// aapt resource value: 0x7f070059
			public const int wbutton_E = 2131165273;
			
			// aapt resource value: 0x7f070064
			public const int wbutton_F = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int wbutton_G = 2131165285;
			
			// aapt resource value: 0x7f070066
			public const int wbutton_H = 2131165286;
			
			// aapt resource value: 0x7f07005e
			public const int wbutton_I = 2131165278;
			
			// aapt resource value: 0x7f070067
			public const int wbutton_J = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int wbutton_K = 2131165288;
			
			// aapt resource value: 0x7f070069
			public const int wbutton_L = 2131165289;
			
			// aapt resource value: 0x7f070071
			public const int wbutton_M = 2131165297;
			
			// aapt resource value: 0x7f070070
			public const int wbutton_N = 2131165296;
			
			// aapt resource value: 0x7f07005f
			public const int wbutton_O = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int wbutton_P = 2131165280;
			
			// aapt resource value: 0x7f070057
			public const int wbutton_Q = 2131165271;
			
			// aapt resource value: 0x7f070074
			public const int wbutton_Quote = 2131165300;
			
			// aapt resource value: 0x7f07005a
			public const int wbutton_R = 2131165274;
			
			// aapt resource value: 0x7f070062
			public const int wbutton_S = 2131165282;
			
			// aapt resource value: 0x7f07006a
			public const int wbutton_SHIFT = 2131165290;
			
			// aapt resource value: 0x7f070078
			public const int wbutton_SPACE = 2131165304;
			
			// aapt resource value: 0x7f070077
			public const int wbutton_SemiC = 2131165303;
			
			// aapt resource value: 0x7f07005b
			public const int wbutton_T = 2131165275;
			
			// aapt resource value: 0x7f07005d
			public const int wbutton_U = 2131165277;
			
			// aapt resource value: 0x7f070076
			public const int wbutton_UnderS = 2131165302;
			
			// aapt resource value: 0x7f07006e
			public const int wbutton_V = 2131165294;
			
			// aapt resource value: 0x7f070058
			public const int wbutton_W = 2131165272;
			
			// aapt resource value: 0x7f07006c
			public const int wbutton_X = 2131165292;
			
			// aapt resource value: 0x7f07005c
			public const int wbutton_Y = 2131165276;
			
			// aapt resource value: 0x7f07006b
			public const int wbutton_Z = 2131165291;
			
			// aapt resource value: 0x7f070072
			public const int wbutton_delete = 2131165298;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int message = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int nconnect = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int nlist = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int overview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Secret = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int slide_up = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int splashmodel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int viewmodel_maina = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int wifi_maina = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AlertTheme = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int AppTheme = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int FullscreenActionBarStyle = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int FullscreenTheme = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int MyAlertDialogTheme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int NXKBSyle = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int NXKBSyleN = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int NXKBSyleS = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Widget = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Widget_DescriptionBar = 2131034118;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ButtonBarContainerTheme = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int ButtonBarContainerTheme_metaButtonBarButtonStyle = 1;
			
			// aapt resource value: 0
			public const int ButtonBarContainerTheme_metaButtonBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
